# Generated by Django 6.0 on 2026-01-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_course_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_semester', models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2')], default=1, help_text='Currently active semester')),
                ('academic_year', models.CharField(default='2024/2025', help_text='Current academic year (e.g., 2024/2025)', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
