# Generated by Django 6.0 on 2026-01-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_course_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='room_type',
            field=models.CharField(choices=[('Lecture Hall', 'Lecture Hall'), ('Computer Lab', 'Computer Lab')], max_length=20),
        ),
    ]
