# Generated by Django 6.0 on 2026-01-03 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_classroom_is_active_alter_classroom_room_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='year',
        ),
        migrations.AddField(
            model_name='subject',
            name='room_type',
            field=models.CharField(choices=[('Lecture Hall', 'Lecture Hall'), ('Computer Lab', 'Computer Lab')], default='Lecture Hall', max_length=20),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='capacity',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='subject',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(choices=[(1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='weekly_hours',
            field=models.IntegerField(default=3),
        ),
    ]
