# Generated by Django 6.0 on 2026-01-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='is_timetable_published',
            field=models.BooleanField(default=False, help_text='If true, timetable is visible to students and lecturers'),
        ),
    ]
