# Generated by Django 6.0 on 2026-01-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_lecturerprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturerprofile',
            name='availability',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
